#pragma once
#include "slang.h"

namespace Native
{
    enum ResourceShape
    {
        RESOURCE_BASE_SHAPE_MASK = 0x0F,

        RESOURCE_NONE = 0x00,

        TEXTURE_1D = 0x01,
        TEXTURE_2D = 0x02,
        TEXTURE_3D = 0x03,
        TEXTURE_CUBE = 0x04,
        TEXTURE_BUFFER = 0x05,

        STRUCTURED_BUFFER = 0x06,
        BYTE_ADDRESS_BUFFER = 0x07,
        RESOURCE_UNKNOWN = 0x08,
        ACCELERATION_STRUCTURE = 0x09,
        TEXTURE_SUBPASS = 0x0A,

        RESOURCE_EXT_SHAPE_MASK = 0xF0,

        TEXTURE_FEEDBACK_FLAG = 0x10,
        TEXTURE_SHADOW_FLAG = 0x20,
        TEXTURE_ARRAY_FLAG = 0x40,
        TEXTURE_MULTISAMPLE_FLAG = 0x80,

        TEXTURE_1D_ARRAY = SLANG_TEXTURE_1D | SLANG_TEXTURE_ARRAY_FLAG,
        TEXTURE_2D_ARRAY = SLANG_TEXTURE_2D | SLANG_TEXTURE_ARRAY_FLAG,
        TEXTURE_CUBE_ARRAY = SLANG_TEXTURE_CUBE | SLANG_TEXTURE_ARRAY_FLAG,

        TEXTURE_2D_MULTISAMPLE = SLANG_TEXTURE_2D | SLANG_TEXTURE_MULTISAMPLE_FLAG,
        TEXTURE_2D_MULTISAMPLE_ARRAY =
        TEXTURE_2D | SLANG_TEXTURE_MULTISAMPLE_FLAG | SLANG_TEXTURE_ARRAY_FLAG,
        TEXTURE_SUBPASS_MULTISAMPLE = SLANG_TEXTURE_SUBPASS | SLANG_TEXTURE_MULTISAMPLE_FLAG,
    };
}
