#pragma once

namespace Native
{
    enum ResourceAccess
    {
        RESOURCE_ACCESS_NONE,
        RESOURCE_ACCESS_READ,
        RESOURCE_ACCESS_READ_WRITE,
        RESOURCE_ACCESS_RASTER_ORDERED,
        RESOURCE_ACCESS_APPEND,
        RESOURCE_ACCESS_CONSUME,
        RESOURCE_ACCESS_WRITE,
        RESOURCE_ACCESS_FEEDBACK,
        RESOURCE_ACCESS_UNKNOWN = 0x7FFFFFFF,
    };
}
